---
- name: Automate web server
  hosts: hw1
  become: yes
  gather_facts: no
  tasks:
  - name: update
    apt:
        update_cache=yes
  - name: install apache2
    apt: 
        name=apache2 
        update_cache=yes
        state=present
  - name: restart apache2
    service:
        name=apache2 
        state=restarted
  - name: git pull
    git:
        repo=https://github.com/jackiequach/cse356hw1.git 
        dest=/home/ubuntu/cse356hw1
  - name: move html file to web server
    copy:
        src=/home/ubuntu/cse356hw1/hw0.html
        dest=/var/www/html/hw0.html
  - name: delete tmp dir
    file:
        path: /home/ubuntu/cse356hw1
        state: absent