---
- name: Automate web server
  hosts: hw1
  become: yes
  gather_facts: no
  sudo: yes  
  tasks:
  - name: install apache2
	apt: 
		name=apache2 
		update_cache=yes
        state=present
  - name: restart apache2
	service:
		name=apache2 
        state=restarted
  - name: git pull
    git:
        repo=https://github.com/jackiequach/cse356hw1.git 
        dest=/home/ubuntu/tmp
  - name: move html file to web server
    copy:
        src: /home/ubuntu/tmp/hw0.html
        dest: /var/www/html/hw0.html
  - name: delete tmp dir
    file:
        path: /home/ubuntu/tmp
        state: absent